.TH serviceconf 8 "Wed May 16 2001"
.SH "NAME"
system-config-services \- Service Configuration Utility
.SH "SYNOPSIS"
system-config-services
.SH "DESCRIPTION"
This is a graphical tool for enabling and disabling services
(including xinetd services). Functionality to start, stop, and restart
services is also included.
.SH "OPTIONS"
None
.SH "FILES"
.nf
\fI/usr/bin/system-config-services\fP
\fI/usr/share/system-config-services/*\fP
.fi
.SH "EXAMPLES"
To run this program simply type:
.LP 
system-config-services
.LP 

.SH "SEE ALSO"
.IR chkconfig(8)
.IR ntsysv(8)

.SH "BUGS"
\- Some services will not start or stop properly if started anywhere
but the console (system-config-services will appear to hang in these
instances). This is not a bug in system-config-services, but in the individual
services.

\- Some services are incredibly hard to detect if they are running or
not. While there are workarounds present to deal with these, it can't be
guaranteed that they're detected properly. Please file bugs against the
system-config-services component at http://bugzilla.redhat.com if you encounter
such services.

.SH "AUTHORS"
.nf
Tim Powers <timp@redhat.com>
Bill Nottingham <notting@redhat.com>
Dan Walsh <dwalsh@redhat.com>
Nils Philippsen <nphilipp@redhat.com>
.fi
